// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5i9akNTE9IhZZ5YLQjhj1094uhBCSQ8s',
    appId: '1:1049373535668:web:9e588ec41ff65ffee256e1',
    messagingSenderId: '1049373535668',
    projectId: 'saojosea',
    authDomain: 'saojosea.firebaseapp.com',
    storageBucket: 'saojosea.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyCgifjwFXGaZyZHdtas6mQgtBy3BQMHc',
    appId: '1:1049373535668:android:b582cd748110087ee256e1',
    messagingSenderId: '1049373535668',
    projectId: 'saojosea',
    storageBucket: 'saojosea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTB78ijZbE551TnD4iX0Kf6sjC7OwTg1o',
    appId: '1:1049373535668:ios:c5b14dc84dae193fe256e1',
    messagingSenderId: '1049373535668',
    projectId: 'saojosea',
    storageBucket: 'saojosea.firebasestorage.app',
    iosBundleId: 'com.jose.paroquiaSaoJoseOsasco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTB78ijZbE551TnD4iX0Kf6sjC7OwTg1o',
    appId: '1:1049373535668:ios:c5b14dc84dae193fe256e1',
    messagingSenderId: '1049373535668',
    projectId: 'saojosea',
    storageBucket: 'saojosea.firebasestorage.app',
    iosBundleId: 'com.jose.paroquiaSaoJoseOsasco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5i9akNTE9IhZZ5YLQjhj1094uhBCSQ8s',
    appId: '1:1049373535668:web:5c8d9a7a22eb8d7be256e1',
    messagingSenderId: '1049373535668',
    projectId: 'saojosea',
    authDomain: 'saojosea.firebaseapp.com',
    storageBucket: 'saojosea.firebasestorage.app',
  );

}