// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRAH2EJa8QL4vTbppEbPIDKgtZwD8CHU',
    appId: '1:570436647717:web:765549a3a0fcdc65f578cc',
    messagingSenderId: '570436647717',
    projectId: 'paroquia-sao-jose-osasco',
    authDomain: 'paroquia-sao-jose-osasco.firebaseapp.com',
    databaseURL: 'https://paroquia-sao-jose-osasco-default-rtdb.firebaseio.com',
    storageBucket: 'paroquia-sao-jose-osasco.appspot.com',
    measurementId: 'G-M53S5Q93X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUduZDQmbTVRwRqFFOgkEGPF1afUc7ZQ4',
    appId: '1:570436647717:android:bbcf3d32289dfe1df578cc',
    messagingSenderId: '570436647717',
    projectId: 'paroquia-sao-jose-osasco',
    databaseURL: 'https://paroquia-sao-jose-osasco-default-rtdb.firebaseio.com',
    storageBucket: 'paroquia-sao-jose-osasco.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYUq9Qtab9GUcNy4yA8mHOeBF6gToXU6k',
    appId: '1:570436647717:ios:808670d5e9e8e8e8f578cc',
    messagingSenderId: '570436647717',
    projectId: 'paroquia-sao-jose-osasco',
    databaseURL: 'https://paroquia-sao-jose-osasco-default-rtdb.firebaseio.com',
    storageBucket: 'paroquia-sao-jose-osasco.appspot.com',
    iosBundleId: 'com.example.paroquiaSaoJoseOsasco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYUq9Qtab9GUcNy4yA8mHOeBF6gToXU6k',
    appId: '1:570436647717:ios:c68a673eb0ed5023f578cc',
    messagingSenderId: '570436647717',
    projectId: 'paroquia-sao-jose-osasco',
    databaseURL: 'https://paroquia-sao-jose-osasco-default-rtdb.firebaseio.com',
    storageBucket: 'paroquia-sao-jose-osasco.appspot.com',
    iosBundleId: 'com.example.paroquiaSaoJoseOsasco.RunnerTests',
  );
}
